// 由 `npm run logos:fetch` 生成（scripts/fetch-logos.ts）。公司 id → /logos/<file>，仅含拉取成功的公司。
// 勿手改；重新生成会先清空 public/logos/。未入表的公司由 LogoSeal 回退首字方印。
export const LOGOS: Record<string, string> = {
  "openai": "/logos/openai.svg",
  "google": "/logos/google.png",
  "anthropic": "/logos/anthropic.png",
  "nvidia": "/logos/nvidia.svg",
  "alibaba": "/logos/alibaba.svg",
  "meta": "/logos/meta.jpg",
  "microsoft": "/logos/microsoft.ico",
  "moonshot": "/logos/moonshot.ico",
  "kuaishou": "/logos/kuaishou.png",
  "xai": "/logos/xai.png",
  "minimax": "/logos/minimax.ico",
  "modelbest": "/logos/modelbest.png",
  "sensetime": "/logos/sensetime.ico",
  "jd": "/logos/jd.png",
  "tencent": "/logos/tencent.png",
  "shanghaiailab": "/logos/shanghaiailab.png",
  "databricks": "/logos/databricks.svg",
  "cerebras": "/logos/cerebras.png",
  "vercel": "/logos/vercel.svg",
  "github": "/logos/github.png",
  "sourcegraph": "/logos/sourcegraph.png",
  "firecrawl": "/logos/firecrawl.png",
  "exa": "/logos/exa.png",
  "zhipu": "/logos/zhipu.png",
  "openrouter": "/logos/openrouter.png",
  "deepseek": "/logos/deepseek.png",
  "bytedance": "/logos/bytedance.ico",
  "xiaomi": "/logos/xiaomi.ico",
  "xiaohongshu": "/logos/xiaohongshu.ico",
  "huggingface": "/logos/huggingface.png",
  "apple": "/logos/apple.svg",
  "midjourney": "/logos/midjourney.png",
  "stabilityai": "/logos/stabilityai.webp",
  "blackforestlabs": "/logos/blackforestlabs.png",
};
